Hw 1
BorisovDm/mlschool_cian pull request #1
Opened 2019-07-18 20:55 UTC by BorisovDm

2019-07-23 13:49 UTC, b2arn requested changes
4 задание не выполнено, по 2 и 3 есть замечания

2019-07-23 13:49 UTC, b2arn commented on homework_1/requirements.txt
> +confluent-kafka
лучше прибивать версию, если ты пишешь зависимости

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_2.py
> +    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
`datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')`

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_2.py
> +from confluent_kafka import Producer
тут должна быть новая строка перед импортом https://www.python.org/dev/peps/pep-0008/#imports

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_2.py
> +        p.produce(topic=OUTPUT_TOPIC, key=key, value=value)
в confluent kafka продьюсер является асинхронным продьюсером и нужно делать poll

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_3.py
> +from multiprocessing import Pool
неправильный порядок импортов

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_3.py
> +            with open(f'{msg.topic()}_{msg.partition()}', 'a') as f:
открывать файл на каждую запись - довольно дорого, лучше открыть их и закрывать вместе с консьюмером

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_3.py
> +        consumer.subscribe([TOPIC_NAME])
этот кусок кода лучше перенести в consume_data

2019-07-23 13:49 UTC, b2arn commented on homework_1/task_4.hql
> +SELECT announcementid, lat, lng, description, address, floornumber, floorscount, category, roomscount, totalarea, price, pricetype, status, dateinserted, TO_DATE('2019-07-01') AS ptn_dadd
Требуется из parsed брать только самые последние изменения и применять только их к lst за предыдущий день

2019-07-24 12:41 UTC, BorisovDm commented on homework_1/requirements.txt
> +confluent-kafka
Да, согласен

2019-07-24 12:44 UTC, BorisovDm commented on homework_1/task_2.py
> +    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
Тут не согласен.
В задании нужен формат 'YYYY-mm-dd HH:MM:SS.sss', то есть с миллисекундами. `datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S')` - вывод без миллисекунд. В моём варианте выдается 6 чисел в миллисекундах, поэтому я последние 3 обрезаю.

2019-07-24 12:58 UTC, b2arn commented on homework_1/task_2.py
> +    timestamp = datetime.datetime.now().strftime('%Y-%m-%d %H:%M:%S.%f')[:-3]
Да, посмотрел задание, тут у тебя все правильно

2019-07-24 13:01 UTC, BorisovDm commented on homework_1/task_2.py
> +from confluent_kafka import Producer
Согласен

2019-07-24 13:04 UTC, BorisovDm commented on homework_1/task_3.py
> +from multiprocessing import Pool
Мда, я придерживался такой схемой импортов: простые import отсортированные лексиграфически, затем from ... import ... тоже  отсортированные лексиграфически. Что не совпадает со схемой импортов по PEP8

2019-07-24 13:37 UTC, b2arn commented on homework_1/task_3.py
> +from multiprocessing import Pool
сначала импорты из стандартных библиотек, потом пустая строка, потом устанавливаемые пакеты, потом пустая строка и локальные модули

2019-07-25 11:01 UTC, BorisovDm commented on homework_1/task_3.py
> +        consumer.subscribe([TOPIC_NAME])
Не совсем понятно. Что я могу перенести в consume_data?
1) Убрать проверку `if is_subscribe` и выполнять `consumer.subscribe([TOPIC_NAME])` только в consume_data - это вроде ок, я согласен
2) `'group.id'` перенести не получится, так как для консьюмера, который узнает количество партиций тоже нужно задать группу, но ее можно задать другую, чтобы не путаться. Но этот консьюмер все равно не будет подписан на топик.

2019-07-25 12:19 UTC, BorisovDm reviewed
[task 2]
1. Добавил пробавил между импортами
2. Добавил вызов poll

[task 3]
1. Поменял порядок импортов
2. Теперь файлы каждый раз не переоткрываются
3. И заметил тот факт, что KeyboardInterrupt ломает только сам Pool, до процессов этот exception не доходит, пофиксил это вызовом метода terminate у pool

2019-07-26 20:49 UTC, BorisovDm reviewed
1. Таблица announcement_lst наконец создалась, прошлый запрос содержал много ошибок.
2. Добавил скрипт заполнения пустой таблицы из prod.announcement_lst
3. Добавил скрипт добавления партиции по предыдущему дню + изменениям за этот день
4. Потестил, работает верно

2019-07-26 20:49 UTC, BorisovDm commented on homework_1/task_4.hql
> +SELECT announcementid, lat, lng, description, address, floornumber, floorscount, category, roomscount, totalarea, price, pricetype, status, dateinserted, TO_DATE('2019-07-01') AS ptn_dadd
fix в новом коммите

2019-07-26 20:50 UTC, BorisovDm commented on homework_1/task_3.py
> +        consumer.subscribe([TOPIC_NAME])
fix в новых коммитах

2019-07-26 20:50 UTC, BorisovDm commented on homework_1/task_3.py
> +            with open(f'{msg.topic()}_{msg.partition()}', 'a') as f:
fix в новых коммитах

2019-07-26 20:51 UTC, BorisovDm commented on homework_1/task_2.py
> +        p.produce(topic=OUTPUT_TOPIC, key=key, value=value)
fix в новых коммитах

2019-07-29 11:36 UTC, b2arn requested changes

2019-07-29 11:36 UTC, b2arn commented on homework_1/task_2.py
> +        p.produce(topic=OUTPUT_TOPIC, key=key, value=value)
poll после produce, flush один раз после того как произошла какая то ошибка и нужно дослать данные и выйти

2019-07-29 11:36 UTC, b2arn commented on homework_1/task_2.py
> +        p.flush()
flush делается вне лупа, в случае если возникает ошибка или продьюсер останавливается каким то другим способом

2019-07-29 11:36 UTC, b2arn commented on homework_1/task_4/3_insert_data_july_3.hql
> +    SELECT *, ROW_NUMBER() OVER (PARTITION BY announcementid ORDER BY dateinserted DESC) rn
в lst и так только последние данные по объявлению, нужно делать window функцию после union all, чтобы получить состояние за позавчера плюс изменения за вчера и получить последнее состояние объявления

2019-07-29 12:00 UTC, BorisovDm commented on homework_1/task_4/3_insert_data_july_3.hql
> +    SELECT *, ROW_NUMBER() OVER (PARTITION BY announcementid ORDER BY dateinserted DESC) rn
А window функция применяется не для lst, а для parsed же, для нее я и получаю последние записи. Правда, я добавляю дополнительную фильтрацию на id для lst таблицы, нужно еще подумать как быстрее - сначала объединить 2 таблицы, а потом брать последние записи, или объединить уже уникальные записи. Первый вариант, наверное, более читаемый.

2019-07-29 13:30 UTC, b2arn approved these changes

2019-07-29 16:50 UTC, merged